### ISSUE TITLE
SFI: ROPC items for remediation

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#10434]
### Describe the issue or suggestion

- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.Configuration/ProcessModelSection.xml	password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.Security/ActiveDirectoryMembershipProvider.xml	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.Security/FormsAuthentication.xml	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.UI.WebControls/ChangePassword.xml	password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.UI.WebControls/CreateUserWizard.xml	ConnectionString,password=
- [x] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.UI.WebControls.WebParts/WebPartZoneBase.xml	ROPC
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/cpp/VS_Snippets_Remoting/Classic HttpWebRequest.ConnectionGroupName Example/CPP/source.cpp	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/System.Net/WebRequest/PreAuthenticate/webrequest_preauthenticate.cs	password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks DbConnectionStringBuilder/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks DbConnectionStringBuilder.Values/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OdbcConnectionStringBuilder/CS/source.cs	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OdbcConnectionStringBuilder.Keys/CS/source.cs	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OdbcConnectionStringBuilder.Multiple/CS/source.cs	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OleDbConnectionStringBuilder.Ctor/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OleDbConnectionStringBuilder.Keys/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OleDbConnectionStringBuilder.Provider/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder.Ctor/CS/source.cs	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder.IntegratedSecurity/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder.Remove/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder.IntegratedSecurity/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder.Password/CS/source.cs	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder.Remove/CS/source.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/c_claimset/cs/service.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/c_iauthorizationpolicy/cs/service.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/c_usernamevalidator/cs/service.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/s_ueservicecredentials/cs/service.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/s_ueusernamepasswordvalidationmode/cs/service.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/s_uewindowsservicecredential/cs/source.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/usernamepasswordservicecredential/cs/source.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_CFX/usernamesecuritytokenauthenticator/cs/mytokenauthenticator.cs	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_WebNet/FormsAuthenticationHashPassword/CS/formsauthenticationhashpasswordcs.aspx	password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_WebNet/System.Web.Management.SqlServices/CS/usingsqlservices.cs	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_WebNet/System.Web.UI.WebControls.ChangePassword.OnChangingPassword/CS/changepassword_cs.aspx	password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/csharp/VS_Snippets_WebNet/System.Web.UI.WebControls.ParameterCollection_2/CS/paramcoll2cs.aspx	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks DbConnectionStringBuilder/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks DbConnectionStringBuilder.Values/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OdbcConnectionStringBuilder/VB/source.vb	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OdbcConnectionStringBuilder.Keys/VB/source.vb	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OdbcConnectionStringBuilder.Multiple/VB/source.vb	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OleDbConnectionStringBuilder.Ctor/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OleDbConnectionStringBuilder.Keys/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OleDbConnectionStringBuilder.Provider/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder.Ctor/VB/source.vb	ConnectionString,pwd=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder.IntegratedSecurity/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks OracleConnectionStringBuilder.Remove/VB/source.vb	ConnectionString,password=
- [x] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder.IntegratedSecurity/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder.Password/VB/source.vb	ConnectionString,pwd=
- [x] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_ADO.NET/DataWorks SqlConnectionStringBuilder.Remove/VB/source.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_CFX/c_usernamevalidator/vb/service.vb	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_CFX/s_uewindowsservicecredential/vb/source.vb	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_CFX/usernamepasswordservicecredential/vb/source.vb	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_CFX/usernamesecuritytokenauthenticator/vb/mytokenauthenticator.vb	UserNamePassword
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_WebNet/FormsAuthenticationHashPassword/VB/formsauthenticationhashpasswordvb.aspx	password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_WebNet/System.Web.Management.SqlServices/VB/usingsqlservices.vb	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_WebNet/System.Web.UI.WebControls.ChangePassword.OnChangingPassword/VB/changepassword_vb.aspx	password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/visualbasic/VS_Snippets_WebNet/System.Web.UI.WebControls.ParameterCollection_2/VB/paramcoll2vb.aspx	ConnectionString,password=
- [ ] https://github.com/dotnet/dotnet-api-docs/blob/main/xml/SourceLinkInformation/net-8.0/System.ServiceModel.Primitives.json	UserNamePassword

---
[Associated WorkItem - 350931](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350931)

**Comment by gewarren** [comment]
@camastr When do these need to be remediated? Can I push this out to December?

**Comment by cmastr** [comment]
> [@cmastr](https://github.com/cmastr) When do these need to be remediated? Can I push this out to December?

So sorry I didn't see this until now.
