### ISSUE TITLE
Reorganize C# snippets based on API name

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#7554]
Organize C# snippets into subfolders based on namespace and type.

Folders to organize:

- [x] samples/snippets/csharp/api
- [x] samples/snippets/csharp/VS_Snippets_CLR
- [x] samples/snippets/csharp/VS_Snippets_CLR_Classic
- [x] samples/snippets/csharp/VS_Snippets_CLR_System
- [x] samples/snippets/csharp/VS_Snippets_CodeAnalysis
- [x] samples/snippets/csharp/VS_Snippets_Data
- [x] samples/snippets/csharp/VS_Snippets_Misc
- [x] samples/snippets/csharp/VS_Snippets_Remoting
- [x] samples/snippets/csharp/VS_Snippets_VBCSharp

Consider for later:

- [x] samples/snippets/csharp/VS_Snippets_WinForms
- [x] samples/snippets/csharp/VS_Snippets_WPF
