### ISSUE TITLE
Scrub outdated APM pattern async

### ISSUE THREAD

**Issue by scalablecory** [dotnet/dotnet-api-docs#7713]
### Edit
*by @antonfirsov*

Let's scope this to the API doc examples, since the conceptual doc concerns have been addressed by https://github.com/dotnet/docs/pull/30759.

Related discussion: #7609

#### TODO
We should modernize (???) or - frankly - just delete APM examples for various classes. As pointed out in https://github.com/dotnet/docs/issues/26911, it is very unfortunate they block the thread with `ManualResetEvent`. Additionally, I find it confusing that they are often working with state classes and variables which are not defined in the example code.

- [ ] `Socket` - [example](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.beginconnect?view=net-6.0#system-net-sockets-socket-beginconnect(system-net-ipaddress-system-int32-system-asynccallback-system-object))
- [ ]  `NetworkStream` - [example](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.beginread?view=net-6.0#examples)
- [ ] `TCPClient` - [example](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.beginconnect?view=net-6.0)
- [ ] `TCPListener` [example](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener.beginacceptsocket?view=net-6.0#examples)
- [ ] `SslStream` - [example](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.beginwrite?view=net-6.0#examples) (somewhat confusing state object)

### Original text

There are various examples showing old pattern async, e.g.:

- https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=net-6.0
- https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream?view=net-6.0

We should update samples to use the TAP pattern when appropriate.

~There are various samples within the Framework docs too, and these show up in search results. We should do something about these. e.g.:~

- https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-an-asynchronous-client-socket
- https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-an-asynchronous-server-socket
- https://docs.microsoft.com/en-us/dotnet/framework/network-programming/http

**Comment by antonfirsov** [comment]
@wfurt @rzikm any thoughts on my list of suggested actions? Do you think the [`SslStream` examples](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.beginwrite?view=net-6.0#examples) are OK? Would you improve or delete them?

**Comment by wfurt** [comment]
I would agree with @scalablecory that we can perhaps delete the examples as the APM pattern is obsolete. If we want to keep it I would remove all the encoding and simplify it as much as possible to simply read bytes to array.

**Comment by rzikm** [comment]
I think we should do what we did for Sockets (?) - mention on all Begin* and End* methods that the pattern is obsolete and point users to *Async methods. And keep usage examples shown on the documentation of the methods themselves but replace them with async/await in overviews/conceptual docs.

**Comment by antonfirsov** [comment]
Closing this in favor of #8508
